# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.10 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================



# -------------------------------------------------------------------------
# These are configurable options:
# -------------------------------------------------------------------------

#  
AR ?= ar

#  
RANLIB ?= ranlib

# C++ compiler 
CXX = g++

# Standard flags for C++ 
CXXFLAGS ?= 

# Standard preprocessor flags (common for CC and CXX) 
CPPFLAGS ?= 

# Standard linker flags 
LDFLAGS ?= 

#  [0,1]
USEDLL ?= 0

#  [0,1]
FINAL ?= 0

#  [0,1]
STATICRTL ?= 0



# -------------------------------------------------------------------------
# Do not modify the rest of this file!
# -------------------------------------------------------------------------

### Variables: ###

CPPDEPS = -MT$@ -MF`echo $@ | sed -e 's,\.o$$,.d,'` -MD -MP
FLAMEROBIN_CXXFLAGS = -D_THREAD_SAFE -pthread $(__DEBUGINFO) $(__OPTIMIZE) -W \
	-Wall $(____flamerobin_WXDEBUG_p) $(____flamerobin_DEBUGFLAG_p) \
	-DIBPP_LINUX -I. -I./src -I./src/ibpp -I./res $(CPPFLAGS) $(CXXFLAGS)
FLAMEROBIN_OBJECTS =  \
	flamerobin_addconstrainthandler.o \
	flamerobin_Config.o \
	flamerobin_DatabaseConfig.o \
	flamerobin_LocalSettings.o \
	flamerobin_ArtProvider.o \
	flamerobin_CodeTemplateProcessor.o \
	flamerobin_FRError.o \
	flamerobin_Observer.o \
	flamerobin_ProgressIndicator.o \
	flamerobin_StringUtils.o \
	flamerobin_Subject.o \
	flamerobin_TemplateProcessor.o \
	flamerobin_URIProcessor.o \
	flamerobin_Visitor.o \
	flamerobin_databasehandler.o \
	flamerobin_MetadataLoader.o \
	flamerobin_frprec.o \
	flamerobin_frutils.o \
	flamerobin_AboutBox.o \
	flamerobin_AdvancedMessageDialog.o \
	flamerobin_AdvancedSearchFrame.o \
	flamerobin_BackupFrame.o \
	flamerobin_BackupRestoreBaseFrame.o \
	flamerobin_BaseDialog.o \
	flamerobin_BaseFrame.o \
	flamerobin_CommandManager.o \
	flamerobin_ConfdefTemplateProcessor.o \
	flamerobin_ContextMenuMetadataItemVisitor.o \
	flamerobin_ControlUtils.o \
	flamerobin_DataGrid.o \
	flamerobin_DataGridRowBuffer.o \
	flamerobin_DataGridRows.o \
	flamerobin_DataGridTable.o \
	flamerobin_DBHTreeControl.o \
	flamerobin_DndTextControls.o \
	flamerobin_LogTextControl.o \
	flamerobin_PrintableHtmlWindow.o \
	flamerobin_TextControl.o \
	flamerobin_CreateIndexDialog.o \
	flamerobin_DataGeneratorFrame.o \
	flamerobin_DatabaseRegistrationDialog.o \
	flamerobin_EditBlobDialog.o \
	flamerobin_EventWatcherFrame.o \
	flamerobin_ExecuteSqlFrame.o \
	flamerobin_ExecuteSql.o \
	flamerobin_FieldPropertiesDialog.o \
	flamerobin_FindDialog.o \
	flamerobin_FRLayoutConfig.o \
	flamerobin_GUIURIHandlerHelper.o \
	flamerobin_HtmlHeaderMetadataItemVisitor.o \
	flamerobin_HtmlTemplateProcessor.o \
	flamerobin_InsertDialog.o \
	flamerobin_InsertParametersDialog.o \
	flamerobin_MainFrame.o \
	flamerobin_MetadataItemPropertiesFrame.o \
	flamerobin_MultilineEnterDialog.o \
	flamerobin_PreferencesDialog.o \
	flamerobin_PreferencesDialogSettings.o \
	flamerobin_PrivilegesDialog.o \
	flamerobin_ProgressDialog.o \
	flamerobin_ReorderFieldsDialog.o \
	flamerobin_RestoreFrame.o \
	flamerobin_ServerRegistrationDialog.o \
	flamerobin_ServiceBaseFrame.o \
	flamerobin_ShutdownStartupBaseFrame.o \
	flamerobin_ShutdownFrame.o \
	flamerobin_SimpleHtmlFrame.o \
	flamerobin_StatementHistoryDialog.o \
	flamerobin_StartupFrame.o \
	flamerobin_StyleGuide.o \
	flamerobin_UserDialog.o \
	flamerobin_UsernamePasswordDialog.o \
	flamerobin_logger.o \
	flamerobin_main.o \
	flamerobin_MasterPassword.o \
	flamerobin_column.o \
	flamerobin_constraints.o \
	flamerobin_CreateDDLVisitor.o \
	flamerobin_database.o \
	flamerobin_domain.o \
	flamerobin_exception.o \
	flamerobin_function.o \
	flamerobin_generator.o \
	flamerobin_Index.o \
	flamerobin_metadataitem.o \
	flamerobin_MetadataItemCreateStatementVisitor.o \
	flamerobin_MetadataItemDescriptionVisitor.o \
	flamerobin_MetadataItemURIHandlerHelper.o \
	flamerobin_MetadataItemVisitor.o \
	flamerobin_MetadataTemplateCmdHandler.o \
	flamerobin_MetadataTemplateManager.o \
	flamerobin_package.o \
	flamerobin_parameter.o \
	flamerobin_privilege.o \
	flamerobin_procedure.o \
	flamerobin_relation.o \
	flamerobin_role.o \
	flamerobin_root.o \
	flamerobin_server.o \
	flamerobin_table.o \
	flamerobin_trigger.o \
	flamerobin_User.o \
	flamerobin_view.o \
	flamerobin_objectdescriptionhandler.o \
	flamerobin_Identifier.o \
	flamerobin_IncompleteStatement.o \
	flamerobin_MultiStatement.o \
	flamerobin_SelectStatement.o \
	flamerobin_SqlStatement.o \
	flamerobin_SqlTokenizer.o \
	flamerobin_StatementBuilder.o \
	flamerobin_statementHistory.o \
	flamerobin_StyleGuideGTK.o
IBPP_CXXFLAGS = -D_THREAD_SAFE -pthread $(__DEBUGINFO) $(__OPTIMIZE) -W -Wall \
	-DIBPP_LINUX -I./src/ibpp $(CPPFLAGS) $(CXXFLAGS)
IBPP_OBJECTS =  \
	ibpp__dpb.o \
	ibpp__ibpp.o \
	ibpp__ibs.o \
	ibpp__rb.o \
	ibpp__spb.o \
	ibpp__tpb.o \
	ibpp_array.o \
	ibpp_blob.o \
	ibpp_database.o \
	ibpp_date.o \
	ibpp_dbkey.o \
	ibpp_events.o \
	ibpp_exception.o \
	ibpp_row.o \
	ibpp_service.o \
	ibpp_statement.o \
	ibpp_time.o \
	ibpp_transaction.o \
	ibpp_user.o

### Conditionally set variables: ###

ifeq ($(FINAL),0)
____flamerobin_WXDEBUG_p = -D__WXDEBUG__
endif
ifeq ($(FINAL),0)
____flamerobin_DEBUGFLAG_p = -D_DEBUG
endif
ifeq ($(FINAL),0)
__DEBUGINFO = -g
endif
ifeq ($(FINAL),1)
__DEBUGINFO = 
endif
ifeq ($(FINAL),0)
__OPTIMIZE = -O0
endif
ifeq ($(FINAL),1)
__OPTIMIZE = -Os
endif


### Targets: ###

all: revision-info flamerobin libibpp.a

install: 

uninstall: 

clean: 
	rm -f ./*.o
	rm -f ./*.d
	rm -f flamerobin
	rm -f libibpp.a

revision-info: 
	update-revision-info.cmd

flamerobin: $(FLAMEROBIN_OBJECTS) libibpp.a libibpp.a
	$(CXX) -o $@ $(FLAMEROBIN_OBJECTS)  -pthread $(__DEBUGINFO)  $(LDFLAGS)  libibpp.a

libibpp.a: $(IBPP_OBJECTS)
	rm -f $@
	$(AR) rcu $@ $(IBPP_OBJECTS)
	$(RANLIB) $@

flamerobin_addconstrainthandler.o: ./src/addconstrainthandler.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_Config.o: ./src/config/Config.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_DatabaseConfig.o: ./src/config/DatabaseConfig.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_LocalSettings.o: ./src/config/LocalSettings.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_ArtProvider.o: ./src/core/ArtProvider.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_CodeTemplateProcessor.o: ./src/core/CodeTemplateProcessor.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_FRError.o: ./src/core/FRError.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_Observer.o: ./src/core/Observer.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_ProgressIndicator.o: ./src/core/ProgressIndicator.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_StringUtils.o: ./src/core/StringUtils.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_Subject.o: ./src/core/Subject.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_TemplateProcessor.o: ./src/core/TemplateProcessor.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_URIProcessor.o: ./src/core/URIProcessor.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_Visitor.o: ./src/core/Visitor.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_databasehandler.o: ./src/databasehandler.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_MetadataLoader.o: ./src/engine/MetadataLoader.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_frprec.o: ./src/frprec.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_frutils.o: ./src/frutils.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_AboutBox.o: ./src/gui/AboutBox.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_AdvancedMessageDialog.o: ./src/gui/AdvancedMessageDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_AdvancedSearchFrame.o: ./src/gui/AdvancedSearchFrame.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_BackupFrame.o: ./src/gui/BackupFrame.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_BackupRestoreBaseFrame.o: ./src/gui/BackupRestoreBaseFrame.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_BaseDialog.o: ./src/gui/BaseDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_BaseFrame.o: ./src/gui/BaseFrame.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_CommandManager.o: ./src/gui/CommandManager.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_ConfdefTemplateProcessor.o: ./src/gui/ConfdefTemplateProcessor.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_ContextMenuMetadataItemVisitor.o: ./src/gui/ContextMenuMetadataItemVisitor.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_ControlUtils.o: ./src/gui/controls/ControlUtils.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_DataGrid.o: ./src/gui/controls/DataGrid.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_DataGridRowBuffer.o: ./src/gui/controls/DataGridRowBuffer.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_DataGridRows.o: ./src/gui/controls/DataGridRows.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_DataGridTable.o: ./src/gui/controls/DataGridTable.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_DBHTreeControl.o: ./src/gui/controls/DBHTreeControl.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_DndTextControls.o: ./src/gui/controls/DndTextControls.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_LogTextControl.o: ./src/gui/controls/LogTextControl.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_PrintableHtmlWindow.o: ./src/gui/controls/PrintableHtmlWindow.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_TextControl.o: ./src/gui/controls/TextControl.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_CreateIndexDialog.o: ./src/gui/CreateIndexDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_DataGeneratorFrame.o: ./src/gui/DataGeneratorFrame.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_DatabaseRegistrationDialog.o: ./src/gui/DatabaseRegistrationDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_EditBlobDialog.o: ./src/gui/EditBlobDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_EventWatcherFrame.o: ./src/gui/EventWatcherFrame.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_ExecuteSqlFrame.o: ./src/gui/ExecuteSqlFrame.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_ExecuteSql.o: ./src/gui/ExecuteSql.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_FieldPropertiesDialog.o: ./src/gui/FieldPropertiesDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_FindDialog.o: ./src/gui/FindDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_FRLayoutConfig.o: ./src/gui/FRLayoutConfig.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_GUIURIHandlerHelper.o: ./src/gui/GUIURIHandlerHelper.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_HtmlHeaderMetadataItemVisitor.o: ./src/gui/HtmlHeaderMetadataItemVisitor.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_HtmlTemplateProcessor.o: ./src/gui/HtmlTemplateProcessor.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_InsertDialog.o: ./src/gui/InsertDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_InsertParametersDialog.o: ./${SOURCEDIR}/gui/InsertParametersDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_MainFrame.o: ./src/gui/MainFrame.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_MetadataItemPropertiesFrame.o: ./src/gui/MetadataItemPropertiesFrame.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_MultilineEnterDialog.o: ./src/gui/MultilineEnterDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_PreferencesDialog.o: ./src/gui/PreferencesDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_PreferencesDialogSettings.o: ./src/gui/PreferencesDialogSettings.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_PrivilegesDialog.o: ./src/gui/PrivilegesDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_ProgressDialog.o: ./src/gui/ProgressDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_ReorderFieldsDialog.o: ./src/gui/ReorderFieldsDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_RestoreFrame.o: ./src/gui/RestoreFrame.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_ServerRegistrationDialog.o: ./src/gui/ServerRegistrationDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_ServiceBaseFrame.o: ./${SOURCEDIR}/gui/ServiceBaseFrame.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_ShutdownStartupBaseFrame.o: ./${SOURCEDIR}/gui/ShutdownStartupBaseFrame.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_ShutdownFrame.o: ./${SOURCEDIR}/gui/ShutdownFrame.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_SimpleHtmlFrame.o: ./src/gui/SimpleHtmlFrame.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_StatementHistoryDialog.o: ./src/gui/StatementHistoryDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_StartupFrame.o: ./${SOURCEDIR}/gui/StartupFrame.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_StyleGuide.o: ./src/gui/StyleGuide.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_UserDialog.o: ./src/gui/UserDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_UsernamePasswordDialog.o: ./src/gui/UsernamePasswordDialog.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_logger.o: ./src/logger.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_main.o: ./src/main.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_MasterPassword.o: ./src/MasterPassword.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_column.o: ./src/metadata/column.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_constraints.o: ./src/metadata/constraints.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_CreateDDLVisitor.o: ./src/metadata/CreateDDLVisitor.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_database.o: ./src/metadata/database.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_domain.o: ./src/metadata/domain.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_exception.o: ./src/metadata/exception.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_function.o: ./src/metadata/function.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_generator.o: ./src/metadata/generator.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_Index.o: ./src/metadata/Index.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_metadataitem.o: ./src/metadata/metadataitem.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_MetadataItemCreateStatementVisitor.o: ./src/metadata/MetadataItemCreateStatementVisitor.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_MetadataItemDescriptionVisitor.o: ./src/metadata/MetadataItemDescriptionVisitor.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_MetadataItemURIHandlerHelper.o: ./src/metadata/MetadataItemURIHandlerHelper.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_MetadataItemVisitor.o: ./src/metadata/MetadataItemVisitor.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_MetadataTemplateCmdHandler.o: ./src/metadata/MetadataTemplateCmdHandler.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_MetadataTemplateManager.o: ./src/metadata/MetadataTemplateManager.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_package.o: ./${SOURCEDIR}/metadata/package.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_parameter.o: ./src/metadata/parameter.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_privilege.o: ./src/metadata/privilege.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_procedure.o: ./src/metadata/procedure.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_relation.o: ./src/metadata/relation.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_role.o: ./src/metadata/role.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_root.o: ./src/metadata/root.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_server.o: ./src/metadata/server.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_table.o: ./src/metadata/table.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_trigger.o: ./src/metadata/trigger.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_User.o: ./src/metadata/User.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_view.o: ./src/metadata/view.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_objectdescriptionhandler.o: ./src/objectdescriptionhandler.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_Identifier.o: ./src/sql/Identifier.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_IncompleteStatement.o: ./src/sql/IncompleteStatement.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_MultiStatement.o: ./src/sql/MultiStatement.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_SelectStatement.o: ./src/sql/SelectStatement.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_SqlStatement.o: ./src/sql/SqlStatement.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_SqlTokenizer.o: ./src/sql/SqlTokenizer.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_StatementBuilder.o: ./src/sql/StatementBuilder.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_statementHistory.o: ./src/statementHistory.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

flamerobin_StyleGuideGTK.o: ./src/gui/gtk/StyleGuideGTK.cpp
	$(CXX) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(CPPDEPS) $<

ibpp__dpb.o: ./src/ibpp/_dpb.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp__ibpp.o: ./src/ibpp/_ibpp.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp__ibs.o: ./src/ibpp/_ibs.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp__rb.o: ./src/ibpp/_rb.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp__spb.o: ./src/ibpp/_spb.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp__tpb.o: ./src/ibpp/_tpb.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp_array.o: ./src/ibpp/array.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp_blob.o: ./src/ibpp/blob.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp_database.o: ./src/ibpp/database.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp_date.o: ./src/ibpp/date.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp_dbkey.o: ./src/ibpp/dbkey.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp_events.o: ./src/ibpp/events.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp_exception.o: ./src/ibpp/exception.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp_row.o: ./src/ibpp/row.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp_service.o: ./src/ibpp/service.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp_statement.o: ./src/ibpp/statement.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp_time.o: ./src/ibpp/time.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp_transaction.o: ./src/ibpp/transaction.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

ibpp_user.o: ./src/ibpp/user.cpp
	$(CXX) -c -o $@ $(IBPP_CXXFLAGS) $(CPPDEPS) $<

.PHONY: all install uninstall clean


# Dependencies tracking:
-include ./*.d
