#!/bin/bash

#####
# postinst script
####

set -o pipefail



### Check to see who executes the `flamerobin` program, then get the personnal directory
#   of this user -> start tag[k0]

# Declaration variables
flagBehalfSudo=""
getPersonalUserDir="$HOME"
getTheRealUser="$USER"

#
if [[ -n "$SUDO_USER" ]]
then
    #
    flagBehalfSudo="$SUDO_USER"
    getTheRealUser="$SUDO_USER"

    # Get the personnel directory of the user
    getPersonalUserDir=$( getent passwd "$flagBehalfSudo" | cut -d ":" -f6 )
fi

### Check to see who executes the `flamerobin` program, then get the personnel directory
#   of this user -> end tag[k0]



### Copy the `*.desktop` file of the flamerobin app to an appropriate directory -> start tag[df0]

if [[ ! -e "/usr/local/share/applications/" ]]
then
    mkdir -p  "/usr/local/share/applications" &> /dev/null 

    #
    if [[ $? -ne 0 ]]
    then
        echo "~"
        echo -e "\033[1;031mMissing directory\033[0m -> [/usr/local/share/applications]"

        exit 1
    fi 
fi

#
cp -r /opt/flamerobin/share/applications/flamerobin.desktop /usr/local/share/applications/ || \
    { echo -e "Failed to copy the desktop file [ ...flamerobin.desktop -> /usr/local/share/applications ]"; exit 1; }

#
update-desktop-database /usr/local/share/applications/ &> /dev/null 

### Copy the `*.desktop` file of the flamerobin app to an appropriate directory -> end tag[df0]



# Symbolic link for the executable (flamerobin) 
if [[ -e "/usr/local/bin/" ]] && [[ -d "/usr/local/bin/" ]] && [[ ` echo "$PATH" | grep "\/usr\/local\/bin" ` ]]
then 
    
    #
    ln -sf /opt/flamerobin/bin/flamerobin-launcher /usr/local/bin/flamerobin || \
        { echo -e "Failed to create symlink in [ /usr/local/bin/ ]"; exit 1; }

elif [[ -e "/usr/bin/" ]] && [[ -d "/usr/bin/" ]] && [[ ` echo "$PATH" | grep "\/usr\/bin" ` ]]
then

    #
    ln -sf /opt/flamerobin/bin/flamerobin-launcher /usr/bin/flamerobin || \
        { echo -e "Failed to create symlink in [ /usr/bin/ ]"; exit 1; }
fi



# Just to print the name of the author
echo ""
echo ""
echo "~"

tput setaf 6; tput bold; echo "By Baldé ~" `tput sgr0` 2> /dev/null
