#!/bin/bash 


### Required GLIBC version to use `flamerobin` (>= 0.9.12)


set -eo pipefail 


glibcVersion=$(getconf GNU_LIBC_VERSION | grep -oE '[0-9]+\.[0-9]+')
requiredVersion="2.39"

if [[ ( "$(printf '%s\n' "$requiredVersion" "$glibcVersion" | sort -V | head -n 1)" == "$requiredVersion" ) ]]
then

    # Not necessary to load this lib if the version of GLIBC >= 2.39 
    rm -rf /opt/flamerobin/lib/libc.so*
fi
