/*
  Copyright (c) 2004-2026 The FlameRobin Development Team

  Permission is hereby granted, free of charge, to any person obtaining
  a copy of this software and associated documentation files (the
  "Software"), to deal in the Software without restriction, including
  without limitation the rights to use, copy, modify, merge, publish,
  distribute, sublicense, and/or sell copies of the Software, and to
  permit persons to whom the Software is furnished to do so, subject to
  the following conditions:

  The above copyright notice and this permission notice shall be included
  in all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#include "engine/db/DatabaseFactory.h"
#include "engine/db/IDatabase.h"
#include "engine/db/ITransaction.h"
#include "engine/db/IStatement.h"
#include "engine/db/TestUtils.h"

int main()
{
    const char* envServer = std::getenv("IBPP_TEST_SERVER");
    const std::string serverName = envServer ? envServer : "";
    if (serverName.empty())
    {
        std::cout << "IBPP_TEST_SERVER is not set, skipping DmlReturningTest.\n";
        return 0;
    }

    const std::string dbName = fr_test::getTestDbPath("dml_returning_test");

    // Create DB using FbCpp
    try 
    {
        fr::IDatabasePtr db = fr::DatabaseFactory::createDatabase(fr::DatabaseBackend::FbCpp);
        db->setConnectionString(serverName + ":" + dbName);
        db->setCredentials("SYSDBA", "masterkey");
        db->create(8192, 3);
    }
    catch (const std::exception& e)
    {
        fr_test::printException(e, "create test database");
        return 1;
    }

    bool ok = true;
    std::cout << "Starting DML RETURNING tests...\n";

    try 
    {
        fr::IDatabasePtr db = fr::DatabaseFactory::createDatabase(fr::DatabaseBackend::FbCpp);
        std::string fullConnStr = serverName + ":" + dbName;
        std::cout << "  Connecting to database: " << fullConnStr << "\n";
        db->setConnectionString(fullConnStr);
        db->setCredentials("SYSDBA", "masterkey");
        try {
            db->connect();
            std::cout << "    Connected successfully.\n";
        } catch (const std::exception& e) {
            std::cerr << "    FAILED to connect to " << fullConnStr << " using fb-cpp backend\n";
            throw;
        }

        // Check version - multi-row RETURNING requires FB 5.0+
        std::string version = db->getEngineVersion();
        std::cout << "  Engine version: " << version << "\n";

        fr::DatabaseInfoData dbInfo;
        db->getInfo(&dbInfo);
        std::cout << "  ODS version: " << dbInfo.ods << "." << dbInfo.odsMinor << "\n";

        // FB 5.0+ requires ODS >= 13.1
        bool isFb5 = (dbInfo.ods > 13 || (dbInfo.ods == 13 && dbInfo.odsMinor >= 1));
        bool isFb4 = (dbInfo.ods == 13 && dbInfo.odsMinor == 0);
        bool isFb3 = (dbInfo.ods == 12);

        // Fallback to string parsing if ODS info is missing or ambiguous
        if (dbInfo.ods == 0)
        {
            isFb5 = (version.find("Firebird 5") != std::string::npos || 
                     version.find("Firebird 6") != std::string::npos ||
                     version.find("V5.") != std::string::npos ||
                     version.find("V6.0") != std::string::npos ||
                     version.find("T5.") != std::string::npos ||
                     version.find("T6.") != std::string::npos);
            isFb4 = (version.find("Firebird 4") != std::string::npos || version.find("V4.") != std::string::npos);
            isFb3 = (version.find("Firebird 3") != std::string::npos || version.find("V3.") != std::string::npos);
        }

        std::cout << "  Detected as FB5+: " << (isFb5 ? "YES" : "NO") << "\n";
        std::cout << "  Detected as FB4: " << (isFb4 ? "YES" : "NO") << "\n";
        std::cout << "  Detected as FB3: " << (isFb3 ? "YES" : "NO") << "\n";
        
        fr::ITransactionPtr tr = db->createTransaction();
        tr->start();

        fr::IStatementPtr st = db->createStatement(tr);
        
        std::cout << "  Creating test table...\n";
        st->prepare("CREATE TABLE t1 (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, val VARCHAR(20))");
        st->execute();
        tr->commitRetain();
        
        std::cout << "  Inserting initial data...\n";
        st->prepare("INSERT INTO t1 (val) VALUES ('A')");
        st->execute();
        st->prepare("INSERT INTO t1 (val) VALUES ('B')");
        st->execute();


        // Test 1: Single-row INSERT ... RETURNING (Supported in FB 3+)
        std::cout << "  Testing Single-row INSERT ... RETURNING...\n";
        st->prepare("INSERT INTO t1 (val) VALUES ('C') RETURNING id, val");
        st->execute();
        std::cout << "    Debug: Columns = " << st->getColumnCount() << "\n";
        ok = fr_test::check(st->getColumnCount() == 2, "Single-row INSERT column count") && ok;
        int rows = 0;
        while (st->fetch()) {
            rows++;
            std::cout << "    Debug: Row " << rows << ": id=" << st->getInt32(0) << ", val=[" << st->getString(1) << "]\n";
        }
        ok = fr_test::check(rows == 1, "Single-row INSERT row count") && ok;

        // Test 2: Multiple-row INSERT ... RETURNING (Supported in FB 5+)
        std::cout << "  Testing Multiple-row INSERT ... RETURNING...\n";
        try
        {
            st->prepare("INSERT INTO t1 (val) SELECT val || '2' FROM t1 WHERE val IN ('A', 'B') RETURNING id, val");
            st->execute();
            
            std::cout << "    Debug: Columns = " << st->getColumnCount() << "\n";
            ok = fr_test::check(st->getColumnCount() == 2, "Multi-row INSERT column count") && ok;
            rows = 0;
            while (st->fetch()) {
                rows++;
                std::cout << "    Debug: Row " << rows << ": id=" << st->getInt32(0) << ", val=[" << st->getString(1) << "]\n";
            }
            
            if (isFb5)
                ok = fr_test::check(rows == 2, "Multi-row INSERT row count (FB5)") && ok;
            else
                fr_test::check(false, "Multi-row INSERT should have failed on FB < 5");
        }
        catch (const std::exception& e)
        {
            if (isFb5)
            {
                std::cout << "    Debug: Multi-row INSERT FAILED with exception: " << e.what() << "\n";
                fr_test::printException(e, "Multi-row INSERT");
                ok = false;
            }
            else
            {
                std::cout << "    PASSED: Multi-row INSERT failed as expected on FB < 5\n";
            }
        }

        // Test 3: Multiple-row UPDATE ... RETURNING (Supported in FB 5+)
        std::cout << "  Testing Multiple-row UPDATE ... RETURNING...\n";
        try
        {
            st->prepare("UPDATE t1 SET val = val || '!' WHERE val IN ('A', 'B') RETURNING id, val");
            st->execute();
            
            std::cout << "    Debug: Columns = " << st->getColumnCount() << "\n";
            ok = fr_test::check(st->getColumnCount() == 2, "Multi-row UPDATE column count") && ok;
            rows = 0;
            while (st->fetch()) {
                rows++;
                std::cout << "    Debug: Row " << rows << ": id=" << st->getInt32(0) << ", val=[" << st->getString(1) << "]\n";
            }
            
            if (isFb5)
                ok = fr_test::check(rows == 2, "Multi-row UPDATE row count (FB5)") && ok;
            else
                fr_test::check(false, "Multi-row UPDATE should have failed on FB < 5");
        }
        catch (const std::exception& e)
        {
            if (isFb5)
            {
                std::cout << "    Debug: Multi-row UPDATE FAILED with exception: " << e.what() << "\n";
                fr_test::printException(e, "Multi-row UPDATE");
                ok = false;
            }
            else
            {
                std::cout << "    PASSED: Multi-row UPDATE failed as expected on FB < 5\n";
            }
        }

        // Test 4: MERGE ... RETURNING (Supported in FB 4+ for single row, FB 5+ for multi-row)
        if (isFb4 || isFb5)
        {
            std::cout << "  Testing MERGE ... RETURNING...\n";
            try
            {
                st->prepare("MERGE INTO t1 t USING (SELECT 1 as id, 'A!!' as val FROM rdb$database) s "
                            "ON t.id = s.id "
                            "WHEN MATCHED THEN UPDATE SET t.val = s.val "
                            "RETURNING t.id, t.val");
                st->execute();
                std::cout << "    Debug: Columns = " << st->getColumnCount() << "\n";
                ok = fr_test::check(st->getColumnCount() == 2, "MERGE RETURNING column count") && ok;
                rows = 0;
                while (st->fetch()) {
                    rows++;
                    std::cout << "    Debug: Row " << rows << ": id=" << st->getInt32(0) << ", val=[" << st->getString(1) << "]\n";
                }
                ok = fr_test::check(rows == 1, "MERGE RETURNING row count (singleton)") && ok;
            }
            catch (const std::exception& e)
            {
                std::cout << "    Debug: MERGE RETURNING FAILED with exception: " << e.what() << "\n";
                fr_test::printException(e, "MERGE RETURNING");
                ok = false;
            }
        }
        else
        {
            std::cout << "  Skipping MERGE ... RETURNING (not supported on FB 3)\n";
        }

        tr->commit();
        db->disconnect();
    }
    catch (const std::exception& e)
    {
        fr_test::printException(e, "DmlReturningTest");
        ok = false;
    }

    // Cleanup
    try 
    {
        fr::IDatabasePtr db = fr::DatabaseFactory::createDatabase(fr::DatabaseBackend::FbCpp);
        db->setConnectionString(serverName + ":" + dbName);
        db->setCredentials("SYSDBA", "masterkey");
        db->connect();
        db->drop();
    }
    catch (...) {}

    if (ok)
    {
        std::cout << "ALL DML RETURNING TESTS PASSED\n";
        return 0;
    }
    else
    {
        std::cout << "SOME DML RETURNING TESTS FAILED\n";
        return 1;
    }
}

