if(TARGET firebird)
    return()
endif()

include(CMakeFindDependencyMacro)

set(_FIREBIRD_ROOT "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}")
set(_FIREBIRD_ROOT_DEBUG "${_FIREBIRD_ROOT}/debug")
set(_FIREBIRD_INCLUDE_DIR "${_FIREBIRD_ROOT}/include")
set(_FIREBIRD_LIB_DIR "${_FIREBIRD_ROOT}/lib")
set(_FIREBIRD_LIB_DIR_DEBUG "${_FIREBIRD_ROOT_DEBUG}/lib")
set(_FIREBIRD_BIN_DIR "${_FIREBIRD_ROOT}/bin")
set(_FIREBIRD_BIN_DIR_DEBUG "${_FIREBIRD_ROOT_DEBUG}/bin")

set(_FIREBIRD_SHARED_FILENAME "")

if(NOT WIN32)
    foreach(_FIREBIRD_SHARED_CANDIDATE libfbclient.so libfbclient.dylib)
        if(EXISTS "${_FIREBIRD_LIB_DIR}/${_FIREBIRD_SHARED_CANDIDATE}")
            set(_FIREBIRD_SHARED_FILENAME "${_FIREBIRD_SHARED_CANDIDATE}")
            break()
        endif()
    endforeach()
endif()

add_library(firebird SHARED IMPORTED)

set_target_properties(firebird PROPERTIES
    IMPORTED_CONFIGURATIONS "DEBUG;RELEASE"
    INTERFACE_INCLUDE_DIRECTORIES "${_FIREBIRD_INCLUDE_DIR}"
)

if(WIN32)
    set(_FIREBIRD_IMPLIB_RELEASE "${_FIREBIRD_LIB_DIR}/fbclient_ms.lib")
    set(_FIREBIRD_IMPLIB_DEBUG "${_FIREBIRD_LIB_DIR_DEBUG}/fbclient_ms.lib")
    if(NOT EXISTS "${_FIREBIRD_IMPLIB_DEBUG}")
        set(_FIREBIRD_IMPLIB_DEBUG "${_FIREBIRD_IMPLIB_RELEASE}")
    endif()

    set(_FIREBIRD_DLL_RELEASE "${_FIREBIRD_BIN_DIR}/fbclient.dll")
    set(_FIREBIRD_DLL_DEBUG "${_FIREBIRD_BIN_DIR_DEBUG}/fbclient.dll")
    if(NOT EXISTS "${_FIREBIRD_DLL_DEBUG}")
        set(_FIREBIRD_DLL_DEBUG "${_FIREBIRD_DLL_RELEASE}")
    endif()

    set_target_properties(firebird PROPERTIES
        IMPORTED_IMPLIB_RELEASE "${_FIREBIRD_IMPLIB_RELEASE}"
        IMPORTED_IMPLIB_DEBUG "${_FIREBIRD_IMPLIB_DEBUG}"
        IMPORTED_LOCATION_RELEASE "${_FIREBIRD_DLL_RELEASE}"
        IMPORTED_LOCATION_DEBUG "${_FIREBIRD_DLL_DEBUG}"
    )
else()
    set(_FIREBIRD_SHARED_RELEASE "${_FIREBIRD_LIB_DIR}/${_FIREBIRD_SHARED_FILENAME}")
    set(_FIREBIRD_SHARED_DEBUG "${_FIREBIRD_LIB_DIR_DEBUG}/${_FIREBIRD_SHARED_FILENAME}")
    if(NOT EXISTS "${_FIREBIRD_SHARED_DEBUG}")
        set(_FIREBIRD_SHARED_DEBUG "${_FIREBIRD_SHARED_RELEASE}")
    endif()

    set_target_properties(firebird PROPERTIES
        IMPORTED_LOCATION_RELEASE "${_FIREBIRD_SHARED_RELEASE}"
        IMPORTED_LOCATION_DEBUG "${_FIREBIRD_SHARED_DEBUG}"
    )
endif()
