/*
  The contents of this file are subject to the Initial Developer's Public
  License Version 1.0 (the "License"); you may not use this file except in
  compliance with the License. You may obtain a copy of the License here:
  http://www.flamerobin.org/license.html.

  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.

  The Original Code is FlameRobin (TM).

  The Initial Developer of the Original Code is Milan Babuskov.

  Portions created by the original developer
  are Copyright (C) 2004 Milan Babuskov.

  All Rights Reserved.

  Contributor(s):
*/

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

// for all others, include the necessary headers (this file is usually all you
// need because it includes almost all "standard" wxWindows headers
#ifndef WX_PRECOMP
    #include "wx/wx.h"
#endif

// -*- C++ -*- generated by wxGlade 0.2.1 on Tue Mar 18 01:08:13 2003
// For compilers that support precompilation, includes "wx/wx.h".
#include <vector>
#include <string>
#include "ibpp.h"
#include "MainFrame.h"
#include "main.h"
//-----------------------------------------------------------------------------
IMPLEMENT_APP(FRApp)
//-----------------------------------------------------------------------------
void FRApp::OnFatalException()
{
    ::wxMessageBox(::wxGetTranslation(
		wxT("A fatal error has occured, the program will be closed.\n\n")
		wxT("If you know how to reproduce the problem,\n")
		wxT("please submit the bug report at:\n")
		wxT("http://sourceforge.net/tracker/?group_id=73595&atid=538266")),
		_("Fatal error"), wxOK | wxICON_ERROR
	);
}
//-----------------------------------------------------------------------------
bool FRApp::OnInit()
{
	// Uncomment this before building a release
	// I don't use it while developing since I cannot catch some errors with debugger then
#if wxUSE_ON_FATAL_EXCEPTION
    ::wxHandleFatalExceptions();
#endif

    // initialize IBPP library - if it fails: exit
    if (! IBPP::CheckVersion(IBPP::Version))
    {
        wxMessageBox(_("Wrong IBPP version."), _("Error."), wxOK | wxICON_ERROR);
        return false;
    }

    wxImage::AddHandler(new wxPNGHandler);

    MainFrame* main_frame = new MainFrame(0, -1, wxT(""));
    SetTopWindow(main_frame);
    main_frame->Show();

    return true;
}
//-----------------------------------------------------------------------------
