/*
  The contents of this file are subject to the Initial Developer's Public
  License Version 1.0 (the "License"); you may not use this file except in
  compliance with the License. You may obtain a copy of the License here:
  http://www.flamerobin.org/license.html.

  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.

  The Original Code is FlameRobin (TM).

  The Initial Developer of the Original Code is Milan Babuskov.

  Portions created by the original developer
  are Copyright (C) 2004 Milan Babuskov.

  All Rights Reserved.

  Contributor(s): Nando Dessena
*/

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

// for all others, include the necessary headers (this file is usually all you
// need because it includes almost all "standard" wxWindows headers
#ifndef WX_PRECOMP
    #include "wx/wx.h"
#endif
//-----------------------------------------------------------------------------
// -*- C++ -*- generated by wxGlade 0.2.2 on Mon Aug 23 09:41:55 2004

#include "ugly.h"
#include "config.h"
#include "images.h"
#include "metadata/table.h"
#include "metadata/view.h"
#include "MetadataItemPropertiesDialog.h"
//-----------------------------------------------------------------------------
MetadataItemPropertiesDialog::MetadataItemPropertiesDialog(wxWindow* parent, YxMetadataItem *object, int id):
    BaseFrame(parent, id, wxT(""))
{
	pageTypeM = ptSummary;
    storageNameM = "unassigned";

	if (!object)
	{
		::wxMessageBox(wxT("MIPD::ctor, Object == 0"), _("Error!"), wxOK);
		return;
	}

    window_1 = new myHtmlWindow(this, -1);
	objectM = object;
	objectM->attach(this);

	CreateStatusBar();
	wxString title = std2wx(objectM->getName()).c_str();
	window_1->SetRelatedFrame(this, title + wxT(": %s"));
	window_1->SetRelatedStatusBar(0);
	SetTitle(wxString::Format(_("%s: properties"), std2wx(objectM->getName()).c_str()));

	update();	// initial rendering

    wxBitmap bmp = getImage32(objectM->getType());
    wxIcon icon;
    icon.CopyFromBitmap(bmp);
    SetIcon(icon);

    set_properties();
    do_layout();
}
//-----------------------------------------------------------------------------
void MetadataItemPropertiesDialog::set_properties()
{
}
//-----------------------------------------------------------------------------
void MetadataItemPropertiesDialog::do_layout()
{
    // begin wxGlade: MetadataItemPropertiesDialog::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxHORIZONTAL);
    sizer_1->Add(window_1, 1, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}
//-----------------------------------------------------------------------------

