/*
  The contents of this file are subject to the Initial Developer's Public
  License Version 1.0 (the "License"); you may not use this file except in
  compliance with the License. You may obtain a copy of the License here:
  http://www.flamerobin.org/license.html.

  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.

  The Original Code is FlameRobin (TM).

  The Initial Developer of the Original Code is Milan Babuskov.

  Portions created by the original developer
  are Copyright (C) 2004 Milan Babuskov.

  All Rights Reserved.

  $Id$

  Contributor(s): Michael Hieke, Nando Dessena
*/

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

// for all others, include the necessary headers (this file is usually all you
// need because it includes almost all "standard" wxWindows headers
#ifndef WX_PRECOMP
    #include "wx/wx.h"
#endif
//-----------------------------------------------------------------------------
// -*- C++ -*- generated by wxGlade 0.2.2 on Fri Aug 27 10:36:29 2004

#include <string>
#include "MultilineEnterDialog.h"
#include "styleguide.h"
//-----------------------------------------------------------------------------
bool GetMultilineTextFromUser(const wxString& caption, wxString& default_value, wxWindow *parent)
{
	wxString result(default_value);
	MultilineEnterDialog med(parent, caption, &result);
	if (wxOK == med.ShowModal())
	{
		default_value = result;
		return true;
	}

	return false;
}
//-----------------------------------------------------------------------------
BEGIN_EVENT_TABLE(MultilineEnterDialog, BaseDialog)
    EVT_BUTTON(MultilineEnterDialog::ID_button_ok, MultilineEnterDialog::OnOkButtonClick)
END_EVENT_TABLE()
//-----------------------------------------------------------------------------
void MultilineEnterDialog::OnOkButtonClick(wxCommandEvent& WXUNUSED(event))
{
	*value = text_ctrl_1->GetValue();
	EndModal(wxOK);
}
//-----------------------------------------------------------------------------
//void MultilineEnterDialog::OnCancelButtonClick(wxCommandEvent& WXUNUSED(event))
//-----------------------------------------------------------------------------
MultilineEnterDialog::MultilineEnterDialog(wxWindow* parent, const wxString& title, wxString* initialText):
    BaseDialog(parent, -1, title)
{
    value = initialText;
    text_ctrl_1 = new wxTextCtrl(this, -1, *initialText, wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    button_ok = new wxButton(this, ID_button_ok, _("OK"));
    button_cancel = new wxButton(this, ID_button_cancel, _("Cancel"));
    do_layout();
    button_ok->SetDefault();
}
//-----------------------------------------------------------------------------
void MultilineEnterDialog::do_layout()
{
	wxBoxSizer* sizerControls = new wxBoxSizer(wxHORIZONTAL);
	text_ctrl_1->SetSizeHints(300, 150);
	text_ctrl_1->SetSize(300, 150);
	sizerControls->Add(text_ctrl_1, 1, wxEXPAND);
	wxSizer* sizerButtons = styleguide().createButtonSizer(button_ok, button_cancel);
	layoutSizers(sizerControls, sizerButtons, true);
}
//-----------------------------------------------------------------------------
const std::string MultilineEnterDialog::getName() const
{
    return "MultilineEnterDialog";
}
//-----------------------------------------------------------------------------
