/*
  The contents of this file are subject to the Initial Developer's Public
  License Version 1.0 (the "License"); you may not use this file except in
  compliance with the License. You may obtain a copy of the License here:
  http://www.flamerobin.org/license.html.

  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.

  The Original Code is FlameRobin (TM).

  The Initial Developer of the Original Code is Milan Babuskov.

  Portions created by the original developer
  are Copyright (C) 2004 Milan Babuskov.

  All Rights Reserved.

  $Id$

  Contributor(s): Michael Hieke, Nando Dessena
*/

// -*- C++ -*- generated by wxGlade 0.2.2 on Fri Aug 27 10:36:29 2004

#ifndef MULTILINEENTERDIALOG_H
#define MULTILINEENTERDIALOG_H

#include <wx/wx.h>
#include "BaseDialog.h"

//-----------------------------------------------------------------------------
bool GetMultilineTextFromUser(const wxString& caption, wxString& default_value, wxWindow *parent=0);
//-----------------------------------------------------------------------------
//! normally you shouldn't need to create objects of this class, just use the GetMultilineTextFromUser function
class MultilineEnterDialog: public BaseDialog {
public:
    // begin wxGlade: MultilineEnterDialog::ids
    enum {
        ID_button_ok = wxID_OK,
        ID_button_cancel = wxID_CANCEL
    };
    // end wxGlade

	void OnOkButtonClick(wxCommandEvent&);
	MultilineEnterDialog(wxWindow* parent, const wxString& title, wxString *initialText);

private:
	wxString *value;

    // begin wxGlade: MultilineEnterDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MultilineEnterDialog::attributes
    wxTextCtrl* text_ctrl_1;
    wxButton* button_ok;
    wxButton* button_cancel;
    // end wxGlade

    DECLARE_EVENT_TABLE()
    virtual const std::string getName() const;
};
//-----------------------------------------------------------------------------
#endif // MULTILINEENTERDIALOG_H
