/*
  The contents of this file are subject to the Initial Developer's Public
  License Version 1.0 (the "License"); you may not use this file except in
  compliance with the License. You may obtain a copy of the License here:
  http://www.flamerobin.org/license.html.

  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.

  The Original Code is FlameRobin (TM).

  The Initial Developer of the Original Code is Milan Babuskov.

  Portions created by the original developer
  are Copyright (C) 2004 Milan Babuskov.

  All Rights Reserved.

  Contributor(s):
*/

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

// for all others, include the necessary headers (this file is usually all you
// need because it includes almost all "standard" wxWindows headers
#ifndef WX_PRECOMP
    #include "wx/wx.h"
#endif

// -*- C++ -*- generated by wxGlade 0.2.2 on Thu Sep 09 11:22:32 2004

#include "ugly.h"
#include "ReorderFieldsDialog.h"

//! included xpm files, so that icons are compiled into executable
namespace reorder_icons {
#include "up.xpm"
#include "down.xpm"
};

ReorderFieldsDialog::ReorderFieldsDialog(wxWindow* parent, YTable *table):
    wxDialog(parent, -1, wxEmptyString, wxDefaultPosition, wxDefaultSize)
{
	tableM = table;
	tableM->checkAndLoadColumns();
	tableM->attach(this);

    // begin wxGlade: ReorderFieldsDialog::ReorderFieldsDialog
    panel_1 = new wxPanel(this, -1);
    const wxString list_box_1_choices[] = {
        _("List of fields")
    };
    list_box_1 = new wxListBox(panel_1, -1, wxDefaultPosition, wxDefaultSize, 1, list_box_1_choices, wxLB_SINGLE);
    button_up = new wxBitmapButton(panel_1, ID_button_up, wxBitmap(reorder_icons::up_xpm));
    button_down = new wxBitmapButton(panel_1, ID_button_down, wxBitmap(reorder_icons::down_xpm));
    button_ok = new wxButton(panel_1, ID_button_ok, _("OK"));
    button_cancel = new wxButton(panel_1, ID_button_cancel, _("Cancel"));

    set_properties();
    do_layout();
    // end wxGlade

    SetTitle(_("Reordering fields of table ") + std2wx(table->getName()));
	update();
}


void ReorderFieldsDialog::set_properties()
{
    // begin wxGlade: ReorderFieldsDialog::set_properties
    SetSize(wxSize(303, 281));
    list_box_1->SetSelection(0);
    button_up->SetSize(wxSize(23, 23));
    button_down->SetSize(wxSize(23, 23));
    button_ok->SetDefault();
    // end wxGlade
}


void ReorderFieldsDialog::do_layout()
{
    // begin wxGlade: ReorderFieldsDialog::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxHORIZONTAL);
    sizer_2->Add(list_box_1, 1, wxALL|wxEXPAND, 5);
    sizer_3->Add(button_up, 0, wxALL, 3);
    sizer_3->Add(button_down, 0, wxALL, 3);
    sizer_5->Add(button_ok, 0, wxALL, 3);
    sizer_5->Add(button_cancel, 0, wxALL, 3);
    sizer_4->Add(sizer_5, 1, wxALIGN_RIGHT, 0);
    sizer_3->Add(sizer_4, 1, wxEXPAND, 0);
    sizer_2->Add(sizer_3, 0, wxALL|wxEXPAND, 2);
    panel_1->SetAutoLayout(true);
    panel_1->SetSizer(sizer_2);
    sizer_2->Fit(panel_1);
    sizer_2->SetSizeHints(panel_1);
    sizer_1->Add(panel_1, 1, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}
