/*
  The contents of this file are subject to the Initial Developer's Public
  License Version 1.0 (the "License"); you may not use this file except in
  compliance with the License. You may obtain a copy of the License here:
  http://www.flamerobin.org/license.html.

  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.

  The Original Code is FlameRobin (TM).

  The Initial Developer of the Original Code is Milan Babuskov.

  Portions created by the original developer
  are Copyright (C) 2004 Milan Babuskov.

  All Rights Reserved.

  Contributor(s):
*/

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

// for all others, include the necessary headers (this file is usually all you
// need because it includes almost all "standard" wxWindows headers
#ifndef WX_PRECOMP
    #include "wx/wx.h"
#endif

// -*- C++ -*- generated by wxGlade 0.2.2 on Thu Sep 09 11:22:32 2004

#include <string>
#include "ugly.h"
#include "urihandler.h"
#include "ExecuteSqlFrame.h"
#include "ReorderFieldsDialog.h"

//-----------------------------------------------------------------------------
BEGIN_EVENT_TABLE(ReorderFieldsDialog, wxDialog)
	EVT_BUTTON(ReorderFieldsDialog::ID_button_ok, ReorderFieldsDialog::OnButtonOkClick)
	EVT_BUTTON(ReorderFieldsDialog::ID_button_cancel, ReorderFieldsDialog::OnButtonCancelClick)
	EVT_BUTTON(ReorderFieldsDialog::ID_button_up, ReorderFieldsDialog::OnButtonUpClick)
	EVT_BUTTON(ReorderFieldsDialog::ID_button_down, ReorderFieldsDialog::OnButtonDownClick)
END_EVENT_TABLE()
//-----------------------------------------------------------------------------
void ReorderFieldsDialog::OnButtonOkClick(wxCommandEvent& WXUNUSED(event))
{
	wxString sql;
	for (int i=0; i<list_box_1->GetCount(); ++i)
		sql += wxT("ALTER TABLE ") + std2wx(tableM->getName()) + wxT(" ALTER ")
			+ list_box_1->GetString(i) + wxT(" POSITION ") + wxString::Format(wxT("%d"), i+1) + wxT(";\n");

	// create ExecuteSqlFrame with option to close at once
    ExecuteSqlFrame *eff = new ExecuteSqlFrame(GetParent(), -1, _("Executing change script"));
	eff->setDatabase(tableM->getDatabase());
	eff->setSql(sql);
	Close();
	eff->executeAllStatements(true);		// true = user must commit/rollback + frame is closed at once
	eff->Show();
}
//-----------------------------------------------------------------------------
void ReorderFieldsDialog::update()
{
	list_box_1->Clear();
	std::vector<YxMetadataItem *> temp;
	tableM->getChildren(temp);
	for (std::vector<YxMetadataItem *>::iterator it = temp.begin(); it != temp.end(); ++it)
		list_box_1->Append(std2wx((*it)->getName()));
}
//-----------------------------------------------------------------------------
//! closes window if table is removed (dropped/disconnected,etc.)
void ReorderFieldsDialog::removeObservedObject(YxSubject *object)
{
	YxObserver::removeObservedObject(object);
	if (object == tableM)
		Close();
}
//-----------------------------------------------------------------------------
void ReorderFieldsDialog::OnButtonCancelClick(wxCommandEvent& WXUNUSED(event))
{
	Close();
}
//-----------------------------------------------------------------------------
void ReorderFieldsDialog::OnButtonUpClick(wxCommandEvent& WXUNUSED(event))
{
	int sel = list_box_1->GetSelection();
	if (sel == -1)
	{
		::wxMessageBox(_("Please select field you wish to move."), _("No field selected."), wxICON_WARNING);
		return;
	}

	if (sel == 0)	// cannot move up more
		return;

	wxString tmp = list_box_1->GetString(sel);
	list_box_1->SetString(sel, list_box_1->GetString(sel-1));
	list_box_1->SetString(sel-1, tmp);
	list_box_1->SetSelection(sel-1);
}
//-----------------------------------------------------------------------------
void ReorderFieldsDialog::OnButtonDownClick(wxCommandEvent& WXUNUSED(event))
{
	int sel = list_box_1->GetSelection();
	if (sel == -1)
	{
		::wxMessageBox(_("Please select field you wish to move."), _("No field selected."), wxICON_WARNING);
		return;
	}

	if (sel == list_box_1->GetCount() - 1)	// cannot move down more
		return;

	wxString tmp = list_box_1->GetString(sel);
	list_box_1->SetString(sel, list_box_1->GetString(sel+1));
	list_box_1->SetString(sel+1, tmp);
	list_box_1->SetSelection(sel+1);
}
//-----------------------------------------------------------------------------
class ReorderFieldsHandler: public YxURIHandler
{
public:
	bool handleURI(std::string& uriStr);
private:
    // singleton; registers itself on creation.
    static const ReorderFieldsHandler handlerInstance;
};
//-----------------------------------------------------------------------------
const ReorderFieldsHandler ReorderFieldsHandler::handlerInstance;
//-----------------------------------------------------------------------------
bool ReorderFieldsHandler::handleURI(std::string& uriStr)
{
    YURI uriObj(uriStr);
	if (uriObj.action != "reorder_fields")
		return false;

	std::string ms = uriObj.getParam("object_address");		// object
	unsigned long mo;
	if (!std2wx(ms).ToULong(&mo))
		return true;
	YTable *t = (YTable *)mo;

	ms = uriObj.getParam("parent_window");		// window
	if (!std2wx(ms).ToULong(&mo))
		return true;
	wxWindow *w = (wxWindow *)mo;

	ReorderFieldsDialog *f = new ReorderFieldsDialog(w, t);
	f->Show();
	return true;
}
//-----------------------------------------------------------------------------
