// -*- C++ -*- generated by wxGlade 0.2.2 on Thu Sep 09 11:22:32 2004

#include <wx/wx.h>
#include <wx/image.h>

#ifndef REORDERFIELDSDIALOG_H
#define REORDERFIELDSDIALOG_H

// begin wxGlade: dependencies
// end wxGlade

#include <string>
#include "observer.h"
#include "metadata/table.h"

class ReorderFieldsDialog: public wxDialog, public YxObserver {
public:
    // begin wxGlade: ReorderFieldsDialog::ids
    enum {
        ID_button_up = 100,
        ID_button_down = 101,
        ID_button_ok = 103,
        ID_button_cancel = 104
    };
    // end wxGlade

    void OnButtonUpClick(wxCommandEvent &event);
    void OnButtonDownClick(wxCommandEvent &event);
    void OnButtonOkClick(wxCommandEvent &event);
    void OnButtonCancelClick(wxCommandEvent &event);

    ReorderFieldsDialog(wxWindow* parent, YTable *table);

private:
	YTable *tableM;

    // begin wxGlade: ReorderFieldsDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ReorderFieldsDialog::attributes
    wxListBox* list_box_1;
    wxBitmapButton* button_up;
    wxBitmapButton* button_down;
    wxButton* button_ok;
    wxButton* button_cancel;
    wxPanel* panel_1;
    // end wxGlade

	void removeObservedObject(YxSubject *object);
	void update();

    DECLARE_EVENT_TABLE()
};


#endif // REORDERFIELDSDIALOG_H
