/*
  The contents of this file are subject to the Initial Developer's Public
  License Version 1.0 (the "License"); you may not use this file except in
  compliance with the License. You may obtain a copy of the License here:
  http://www.flamerobin.org/license.html.

  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.

  The Original Code is FlameRobin (TM).

  The Initial Developer of the Original Code is Milan Babuskov.

  Portions created by the original developer
  are Copyright (C) 2004 Milan Babuskov.

  All Rights Reserved.

  $Id$

  Contributor(s): Nando Dessena, Michael Hieke
*/

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

// for all others, include the necessary headers (this file is usually all you
// need because it includes almost all "standard" wxWindows headers
#ifndef WX_PRECOMP
    #include "wx/wx.h"
#endif

// -*- C++ -*- generated by wxGlade 0.2.2 on Sun Jan 11 15:14:12 2004

#include "ServerRegistrationInfoFrame.h"
#include "ugly.h"
//-----------------------------------------------------------------------------
BEGIN_EVENT_TABLE(ServerRegistrationInfoFrame, BaseDialog)
	EVT_TEXT(ServerRegistrationInfoFrame::ID_textctrl_server, ServerRegistrationInfoFrame::OnSettingsChange)
    EVT_BUTTON(ServerRegistrationInfoFrame::ID_button_ok, ServerRegistrationInfoFrame::OnOkButtonClick)
    EVT_BUTTON(ServerRegistrationInfoFrame::ID_button_cancel, ServerRegistrationInfoFrame::OnCancelButtonClick)
END_EVENT_TABLE()
//-----------------------------------------------------------------------------
void ServerRegistrationInfoFrame::OnSettingsChange(wxCommandEvent& WXUNUSED(event))
{
	if (IsShown())
		updateButtons();
}
//-----------------------------------------------------------------------------
void ServerRegistrationInfoFrame::OnOkButtonClick(wxCommandEvent& WXUNUSED(event))
{
 	serverM->setHostname(wx2std(text_ctrl_1->GetValue()));
 	serverM->setPort(wx2std(text_ctrl_2->GetValue()));
	EndModal(wxOK);
}
//-----------------------------------------------------------------------------
void ServerRegistrationInfoFrame::OnCancelButtonClick(wxCommandEvent& WXUNUSED(event))
{
	EndModal(wxCANCEL);
}
//-----------------------------------------------------------------------------
void ServerRegistrationInfoFrame::setServer(YServer *s)
{
	serverM = s;

 	text_ctrl_1->SetValue(std2wx(serverM->getHostname()));
 	text_ctrl_2->SetValue(std2wx(serverM->getPort()));

	// enable controls depending on operation and database connection status
    // use SetEditable() for edit controls to allow copying text to clipboard
    bool isConnected = serverM->hasConnectedDatabase();
	text_ctrl_1->SetEditable(!isConnected);
	text_ctrl_2->SetEditable(!isConnected);
	button_ok->Enable(!isConnected);
	if (isConnected)
	{
		button_cancel->SetLabel(_("Close"));
		button_cancel->SetDefault();
	};

	updateButtons();
}
//-----------------------------------------------------------------------------
void ServerRegistrationInfoFrame::updateButtons()
{
	button_ok->Enable(text_ctrl_1->IsEditable() && !text_ctrl_1->GetValue().IsEmpty());
}
//-----------------------------------------------------------------------------
const std::string ServerRegistrationInfoFrame::getName() const
{
    return "ServerRegistrationInfoFrame";
}
//-----------------------------------------------------------------------------
