name: Build FlameRobin Snap

on:
  push:
    branches: [ master, dev ]
    tags: [ "v*" ]
  pull_request:
    branches: [ master, dev ]

jobs:
  snap:
    name: Build Snap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build Snap
        uses: snapcore/action-build@v1
        id: build

      - name: Upload Snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: flamerobin-snap
          path: ${{ steps.build.outputs.snap }}
